# Skybreak Configuration
url: http://localhost:4000
webpackURL: http://localhost:8080

http:
  port: 4000

template: 
  file: template.html

public:
  general:
    # Site
    title: iojs vietnam
    description: Bringing ES6 to the Node Community in Vietnam.
    subtitle:
    description:
    author: Hoang Le
    language:
    timezone:

layouts: universe
